### ISSUE TITLE
Voxel doesn't get rendered in Ubuntu

### ISSUE THREAD

**Issue by guts117** [artnas/UnityVoxelMeshGPU#2]
Thanks for this awesome repo!!! 

I am facing some issue while running OutdoorsScene.

There is no voxel rendered while giving these 2 warnings:
1. Shader requires vertex data and is not compatible with DrawNullGeometryIndirect.
2. Attempting to draw with missing bindings

Platform: Ubuntu 22.04.3 LTS
API: Vulkan
Unity version: 2021.3.18f1

I haven't checked on Windows.

**Comment by artnas** [comment]
Hey. I only really use Windows, and I don't see any obvious reasons why it wouldn't work the same on all desktop platforms. Are you using an integrated GPU?

**Comment by guts117** [comment]
Hi. Thanks for the reply!!

I tested it on Windows running on 1080ti with 2021.3.18f1 and  2022.3.35f1.
It works for both Vulkan and DX11.

I have tested it on Ubuntu with different graphic cards (3070 and 4090).
So it seems to be an Ubuntu-only issue.

Update: I managed to run it on Ubuntu with version 2022.3.35f1 and above. 👍

**Comment by guts117** [comment]
I'll close this issue.
Thank you for this awesome project.

**Comment by artnas** [comment]
Thank you, glad it was a matter of updating the editor :)
